package com.yychat.model;

public interface MessageType {
	String LOGIN_VALIDATE_SUCCESS="1";
	String LOGIN_VALIDATE_FAILURE="2";
	String COMMON_CHAT_MESSAGE="3";
	String REQUEST_ONLINE_FRIEND="4";
	String RESPONSE_ONLINE_FRIEND="5";
	String NEW_ONLINE_TO_ALL_FRIEND="6";
	String NEW_ONLINE_FRIEND="7";
	String USER_REGISTER_SUCCESS="8";
	String USER_REGISTER_FAILURE="9";
	String ADD_NEW_FRIEND="10";
	String ADD_NEW_FRIEND_FAILURE_NO_USER="11";
	String ADD_NEW_FRIEND_FAILURE_ALREADY_FRIEND="12";
	String ADD_NEW_FRIEND_SUCCESS="13";
	String UESR_EXIT_SERVER_THREAD_CLOSE="14";
	String UESR_EXIT_CLIENT_THREAD_CLOSE="15";
	String USER_UPDATE_INFO="16";
	String USER_UPDATE_INFO_SUCCESS="17";
	String FLIE_MESSAGE = "18";
	String FRIEND_REQUEST_ACCEPT = "19";
	String FRIEND_REQUEST_UNACCEPT = "20";
	String FRIEND_REQUEST = "21";
}
