version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # 挂载 nginx 配置
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge